### ISSUE TITLE
Error reading SSH protocol banner

### ISSUE THREAD

**Issue by signorrayan** [EntySec/Shreder#4]
Hi, first of all, thanks for this script.
I'm using it as a module, but when i was trying to do dictionary attack, i faced with some errors which i think it is for `parmiko`.
maybe i should post this issue in the parmiko page, but first posting that here, maybe you could handle/fix that in your script.
it guesses the password correctly somtimes, but because of these errors, it has some FalsePositive in each target which returns `None` result.

command: `password = shreder.brute(ip, 22, 'user', 'password.txt')`
target OS: Ubuntu 20.04

Output:
```
Traceback (most recent call last):
  File "/home/pytm/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/pytm/.local/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/home/pytm/.local/lib/python3.8/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pytm/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/home/pytm/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/home/pytm/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/pytm/.local/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/home/pytm/.local/lib/python3.8/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pytm/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/home/pytm/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

```

**Comment by enty8080** [comment]
@signorrayan Hello, how many attempts Shreder passed (?/?)?

**Comment by signorrayan** [comment]
Hi. I'm using a small list ( 56 passwords ), And I'm still having this problem. the target password is in place 18.

**Comment by enty8080** [comment]
@signorrayan It is very strange error because I do not have this problem. Maybe you have slow internet connection or your device has limited login attempts.

**Comment by enty8080** [comment]
@signorrayan I added delay for slow connection and limited login attempts, so you can set it from `0.1` to `10`.

Try reinstall it:

```
pip3 uninstall shreder
pip3 install git+https://github.com/EntySec/Shreder
```

And run:

```python3
password = shreder.brute(ip, 22, 'user', 'password.txt', delay=3)
```
