### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by thecakeisfalse** [EntySec/Shreder#5]
@enty8080

I was trying to connect to target and got this issue

```bash
[*] Processing... | | Passwords tried: 16/9999Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/home/thecakeisfalse/.local/lib/python3.9/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/thecakeisfalse/.local/lib/python3.9/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/home/thecakeisfalse/.local/lib/python3.9/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thecakeisfalse/.local/lib/python3.9/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/home/thecakeisfalse/.local/lib/python3.9/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

**Comment by enty8080** [comment]
Duplicate #4

**Comment by thecakeisfalse** [comment]
@enty8080 i tried different delays (timeouts) and still got this issue

**Comment by enty8080** [comment]
@thecakeisfalse ok

**Comment by thecakeisfalse** [comment]
@enty8080 ggwp
