### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by konn-neko** [EntySec/Shreder#6]
Traceback (most recent call last):
  File "/home/koneko/.local/bin/shreder", line 8, in <module>
    sys.exit(main())
  File "/home/koneko/.local/lib/python3.8/site-packages/shreder/cli.py", line 75, in main
    cli.start()
  File "/home/koneko/.local/lib/python3.8/site-packages/shreder/cli.py", line 48, in start
    self.print_error(f"List file: {self.args.input}: does not exist!")
AttributeError: 'Namespace' object has no attribute 'input'

im on a wsl version of Ubuntu but it does the same thing on a google cloud shell, I'm not sure what caused this, it just happened

**Comment by konn-neko** [comment]
i solved this, it was telling me the file it tried to read was not there
